export const MANAGE_DEV = 'MANAGE_DEV';
export const CREATE_DEV = 'CREATE_DEV'
export const LOAD_DEVS_SUCCESS = 'LOAD_DEVS_SUCCESS'
export const CREATE_DEV_SUCCESS = 'CREATE_DEV_SUCCESS'

export const MANAGE_PEDIDO = 'MANAGE_PEDIDO';
export const CREATE_PEDIDO = 'CREATE_PEDIDO'
export const LOAD_PEDIDOS_SUCCESS = 'LOAD_PEDIDOS_SUCCESS'
export const CREATE_PEDIDO_SUCCESS = 'CREATE_PEDIDO_SUCCESS'

